import {
  LayoutDashboard,
  Upload,
  ShieldCheck,
  FileClock,
  ShoppingCart,
  ReceiptText,
  CalendarCheck,
  UserCheck,
  Zap,
} from "lucide-react";

export const navigation = [
  {
    label: "Dashboard",
    path: "/dashboard",
    icon: LayoutDashboard,
    section: "MAIN",
    navigationCode: "DASHBOARD",
  },
  {
    label: "My Approvals",
    path: "/purchasing/my-approvals",
    icon: UserCheck,
    section: "MAIN",
    navigationCode: "MY_APPROVALS",
  },
  {
    label: "Upload Files",
    path: "/upload-files",
    icon: Upload,
    section: "MAIN",
    navigationCode: "UPLOAD_FILES",
  },
  {
    label: "Purchase Requests",
    path: "/purchasing/requests",
    icon: ShoppingCart,
    section: "MAIN",
    navigationCode: "PURCHASING",
    subItems: [
      { label: "All Requests", path: "/purchasing/requests" },
      { label: "Draft", path: "/purchasing/requests?status=INITIAL" },
      { label: "New Request", path: "/purchasing/requests?status=NEW" },
      { label: "Under Review", path: "/purchasing/requests?status=UNDER_REVIEW" },
      { label: "Waiting Approval", path: "/purchasing/requests?status=WAITING_APPROVAL" },
      { label: "Waiting Payment", path: "/purchasing/requests?status=WAITING_PAYMENT" },
      { label: "Ordered / Purchased", path: "/purchasing/requests?status=PURCHASED" },
      { label: "Shipped", path: "/purchasing/requests?status=SHIPPED" },
      { label: "Goods Received", path: "/purchasing/requests?status=GOODS_RECEIVED" },
      { label: "Completed", path: "/purchasing/requests?status=COMPLETED" },
      { label: "Rejected", path: "/purchasing/requests?status=REJECTED" },
      { label: "On Hold", path: "/purchasing/requests?status=ON_HOLD" },
    ],
  },
  {
    label: "Recurring Payments",
    path: "/purchasing/recurring",
    icon: CalendarCheck,
    section: "MAIN",
    navigationCode: "RECURRING_PAYMENTS",
    // Purchase requesters can open the page to see their own recurring requests.
    alternateNavigationCodes: ["PURCHASING"],
    subItems: [
      { label: "All Subscriptions", path: "/purchasing/recurring" },
      { label: "M&A Scheduled Payments", path: "/purchasing/recurring?filter=MA_SCHEDULED" },
      { label: "Due in 7 Days", path: "/purchasing/recurring?filter=DUE_SOON" },
      { label: "Waiting for Review", path: "/purchasing/recurring?filter=WAITING_REVIEW" },
      { label: "Reviewed (AP)", path: "/purchasing/recurring?filter=REVIEWED" },
      { label: "On Hold", path: "/purchasing/recurring?filter=ON_HOLD" },
      { label: "Completed", path: "/purchasing/recurring?filter=COMPLETED" },
      { label: "Rejected", path: "/purchasing/recurring?filter=REJECTED" },
    ],
  },
  {
    label: "Accounts Payable",
    path: "/purchasing/invoices",
    icon: ReceiptText,
    section: "MAIN",
    navigationCode: "INVOICES",
  },
  {
    label: "Account Receivable",
    path: "/account-receivable",
    icon: ReceiptText,
    section: "MAIN",
    navigationCode: "ACCOUNT_RECEIVABLE",
    subItems: [
      { label: "Overview & Invoices", path: "/account-receivable" },
      { label: "Generate Quote", path: "/account-receivable/generate-quote" },
      { label: "Generate Invoice", path: "/account-receivable/generate" },
    ],
  },
  {
    label: "QuickBooks Sync",
    path: "/purchasing/quickbooks",
    icon: Zap,
    section: "MAIN",
    navigationCode: "PURCHASING",
  },

  {
    label: "System & Security",
    icon: ShieldCheck,
    section: "ADMINISTRATION",
    subItems: [
      { label: "Users", path: "/configurations/users", navigationCode: "CONFIG_USERS" },
      { label: "Roles", path: "/configurations/roles", navigationCode: "CONFIG_ROLES" },
      { label: "Role Assignments", path: "/configurations/user-role-assignment", navigationCode: "CONFIG_USER_ROLE_ASSIGNMENT" },
      { label: "Role Permissions", path: "/configurations/role-group-permissions", navigationCode: "CONFIG_ROLE_API_PERMISSIONS" },
      { label: "MCP Tool Permissions", path: "/configurations/role-mcp-tool-permissions", navigationCode: "CONFIG_ROLE_MCP_TOOL_PERMISSIONS" },
      { label: "Workflow Assignments", path: "/configurations/workflow-assignments", navigationCode: "CONFIG_USER_ROLE_ASSIGNMENT" },
      { label: "Chart of Accounts", path: "/configurations/chart-of-accounts", navigationCode: "CONFIG_CHART_OF_ACCOUNTS" },
      { label: "Payable Contacts", path: "/configurations/payable-contacts", navigationCode: "CONFIG_CHART_OF_ACCOUNTS" },
      { label: "Entities", path: "/configurations/entities", navigationCode: "CONFIG_CHART_OF_ACCOUNTS" },
      { label: "Group Projects", path: "/configurations/projects", navigationCode: "CONFIG_CHART_OF_ACCOUNTS" },
      { label: "Locations", path: "/configurations/locations", navigationCode: "CONFIG_CHART_OF_ACCOUNTS" },
      { label: "Classes", path: "/configurations/classes", navigationCode: "CONFIG_CHART_OF_ACCOUNTS" },
    ]
  },
  {
    label: "Audit Log",
    path: "/log/system-logs",
    icon: FileClock,
    section: "ADMINISTRATION",
    navigationCode: "AUDIT_LOG",
  },
]
